num1String = input('Please enter an integer: ')
num2String = input('Please enter a second integer: ')
num1 = int(num1String)
num2 = int(num2String)
print (num1,' plus ',num2,' equals ',num1+num2)
print (num1, ' subtract',num2, ' equals',num1-num2)
print (num1,' multiply ',num2,' equals ',num1*num2)
print (num1,' divide ',num2,' equals ',num1/num2)
print  (num1,'modulus',num2,'equals',num1%num2)